package synapticloop.sample.h2zero.sqlite3.routemaster.servant;

//- - - - thoughtfully generated by synapticloop h2zero - - - - 
//with the use of synapticloop templar templating language
//  (java-create-routemaster-base-rest-servant.templar)

import java.util.List;
import java.util.Map;

import synapticloop.nanohttpd.router.RestRoutable;

public abstract class BaseServant extends RestRoutable {

	public BaseServant(String routeContext, List<String> params) {
		super(routeContext, params);
	}

	protected String getFirstParameter(String name, Map<String, List<String>> parameters) {
		List<String> list = parameters.get(name);
		if(null == list || list.size() == 0) {
			return(null);
		}

		return(list.get(0));
	}
}
