
//- - - - thoughtfully generated by synapticloop h2zero - - - - 
//with the use of synapticloop templar templating language
//  (java-create-routemaster-base-rest-servant.templar)

import java.sql.Date;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.List;
import java.util.Map;
import org.json.JSONObject;

import synapticloop.nanohttpd.router.RestRoutable;

public abstract class BaseServant extends RestRoutable {
	public class ServantException extends Exception {
		private static final long serialVersionUID = 2662011709175803257L;

		/**
		 * This is an internal exception for indicating that there should be an 
		 * error response
		 * 
		 * @param message The message to give back to the user
		 */
		public ServantException(String message) {
			super(message);
		}
	}

	private static final SimpleDateFormat SIMPLE_DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");

	/**
	 * Instantiate a base servant
	 * 
	 * @param routeContext The route contexts
	 * @param params The list of params to map to
	 */
	public BaseServant(String routeContext, List<String> params) {
		super(routeContext, params);
	}

	/**
	 * Get the first parameter out of the list of parameters
	 * 
	 * @param name The parameter name to look up
	 * @param parameters The map of the parameters for that name
	 * 
	 * @return The first parameter (or null if it does not exist(
	 */
	protected String getFirstParameter(String name, Map<String, List<String>> parameters) {
		List<String> list = parameters.get(name);
		if(null == list || list.size() == 0) {
			return(null);
		}

		return(list.get(0));
	}

	protected String getErrorObjectAsString(String message) {
		JSONObject jsonObject = new JSONObject();
		jsonObject.put("error", message);
		return(jsonObject.toString());
	}

	protected Date castDate(String value) throws ServantException {
		if(null == value) {
			return(null);
		}

		java.util.Date parsed = null;
		try {
			parsed = SIMPLE_DATE_FORMAT.parse(value);
		} catch (ParseException ex) {
			throw new ServantException(ex.getMessage());
		}

		if(null == parsed) {
			return(null);
		}

		return(new Date(parsed.getTime()));
	}

	protected String castString(String value) throws ServantException {
		return(value);
	}

	protected Integer castInteger(String value) throws ServantException {
		if(null == value) {
			return(null);
		}
		try {
			return(Integer.valueOf(value));
		} catch(NumberFormatException ex) {
			throw new ServantException(ex.getMessage());
		}
	}

	protected Boolean castBoolean(String value) throws ServantException {
		if(null == value) {
			return(null);
		}

		return(Boolean.valueOf(value));
	}

	protected Timestamp castTimestamp(String value) throws ServantException {
		if(null == value) {
			return(null);
		}

		try {
			return(Timestamp.valueOf(value));
		} catch(IllegalArgumentException ex) {
			throw new ServantException(ex.getMessage());
		}
	}

	protected Long castLong(String value) throws ServantException {
		if(null == value) {
			return(null);
		}
		try {
			return(Long.valueOf(value));
		} catch(NumberFormatException ex) {
			throw new ServantException(ex.getMessage());
		}
	}

	protected Float castFloat(String value) throws ServantException {
		if(null == value) {
			return(null);
		}
		try {
			return(Float.valueOf(value));
		} catch(NumberFormatException ex) {
			throw new ServantException(ex.getMessage());
		}
	}

}