package synapticloop.sample.h2zero.sqlite3.routemaster.servant;

//- - - - thoughtfully generated by synapticloop h2zero - - - - 
//with the use of synapticloop templar templating language
//        (java-create-routemaster-rest-servant.templar)

import java.io.File;
import java.sql.SQLException;

import java.util.List;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Map;

import fi.iki.elonen.NanoHTTPD.IHTTPSession;
import fi.iki.elonen.NanoHTTPD.Response;
import synapticloop.h2zero.base.exception.H2ZeroFinderException;
import synapticloop.h2zero.base.exception.H2ZeroPrimaryKeyException;
import synapticloop.nanohttpd.utils.HttpUtils;
import synapticloop.sample.h2zero.sqlite3.deleter.UserPetDeleter;
import synapticloop.sample.h2zero.sqlite3.finder.UserPetFinder;
import synapticloop.sample.h2zero.sqlite3.model.UserPet;
import synapticloop.sample.h2zero.sqlite3.model.util.Constants;

public class UserPetServant extends BaseServant {

	private static final String APPLICATION_JSON = "application/json";

	public UserPetServant(String routeContext, List<String> params) {
		super(routeContext, params);
	}

	@Override
	public Response doGet(File rootDir, IHTTPSession httpSession, Map<String, String> restParams, String unmappedParams) {

		if(null != restParams) {
			String primaryKeyString = restParams.get(Constants.USER_PET_ID_USER_PET);
			if(null != primaryKeyString) {
				try {
					Long primaryKey = Long.parseLong(primaryKeyString);
					UserPet userPet = UserPetFinder.findByPrimaryKey(primaryKey);
					return(HttpUtils.okResponse(APPLICATION_JSON, userPet.toJsonString()));
				} catch (NumberFormatException | H2ZeroFinderException ex) {
					return(HttpUtils.badRequestResponse(ex.getMessage()));
				}
			}
		}

		// at this point - there were no parameters, or the parameter was incorrect, so find all

		List<UserPet> findAll;
		try {
			findAll = UserPetFinder.findAll();
		} catch (SQLException ex) {
			return(HttpUtils.internalServerErrorResponse(ex.getMessage()));
		}
		StringBuilder stringBuilder = new StringBuilder("[");
		boolean first = true;
		for (UserPet userPet : findAll) {
			if(!first) {
				stringBuilder.append(",");
			}
			stringBuilder.append(userPet.toJsonString());
			first = false;
		}
		stringBuilder.append("]");
		return(HttpUtils.okResponse(APPLICATION_JSON, stringBuilder.toString()));
	}

	@Override
	public Response doPost(File rootDir, IHTTPSession httpSession, Map<String, String> restParams, String unmappedParams) {
		if(null == httpSession) {
			return(HttpUtils.badRequestResponse());
		}

		Map<String, List<String>> parameters = httpSession.getParameters();

		if(null == parameters) {
			return(HttpUtils.badRequestResponse());
		}

		Long primaryKey = null;
		try {
			Long idUser = castLong(getFirstParameter("idUser", parameters));
			Long idPet = castLong(getFirstParameter("idPet", parameters));
			UserPet userPet = new UserPet(null, idUser, idPet);

			userPet.insert();
			primaryKey = userPet.getPrimaryKey();
		} catch (ServantException | H2ZeroPrimaryKeyException ex) {
			return(HttpUtils.badRequestResponse(APPLICATION_JSON, "{\"error\":\"" + ex.getMessage() + "\"}"));
		} catch (SQLException ex) {
			return(HttpUtils.internalServerErrorResponse(APPLICATION_JSON, "{\"error\":\"" + ex.getMessage() + "\"}"));
		}
		return(HttpUtils.okResponse(APPLICATION_JSON, "{\"primaryKey\": " + primaryKey + "}"));
	}

	@Override
	public Response doPut(File rootDir, IHTTPSession httpSession, Map<String, String> restParams, String unmappedParams) {

		UserPet userPet = null;

		if(null != restParams) {
			String primaryKeyString = restParams.get(Constants.USER_PET_ID_USER_PET);
			if(null != primaryKeyString) {
				try {
					Long primaryKey = Long.parseLong(primaryKeyString);
					userPet = UserPetFinder.findByPrimaryKey(primaryKey);
				} catch (NumberFormatException | H2ZeroFinderException ex) {
					return(HttpUtils.internalServerErrorResponse(ex.getMessage()));
				}
			}
		} else {
			return(HttpUtils.badRequestResponse(APPLICATION_JSON, "{\"error\":\"missing primary key\"}"));
		}

		Map<String, List<String>> parameters = httpSession.getParameters();
		try {
			userPet.setIdUser(castLong(getFirstParameter("idUser", parameters)));
			userPet.setIdPet(castLong(getFirstParameter("idPet", parameters)));

			userPet.update();
		} catch (ServantException | H2ZeroPrimaryKeyException ex) {
			return(HttpUtils.badRequestResponse(APPLICATION_JSON, "{\"error\":\"" + ex.getMessage() + "\"}"));
		} catch (SQLException ex) {
			return(HttpUtils.internalServerErrorResponse(APPLICATION_JSON, "{\"error\":\"" + ex.getMessage() + "\"}"));
		}

		return(HttpUtils.okResponse());
	}

	@Override
	public Response doDelete(File rootDir, IHTTPSession httpSession, Map<String, String> restParams, String unmappedParams) {
		if(null != restParams) {
			String primaryKeyString = restParams.get(Constants.USER_PET_ID_USER_PET);
			if(null != primaryKeyString) {
				try {
					Long primaryKey = Long.parseLong(primaryKeyString);
					int numDeleted = UserPetDeleter.deleteByPrimaryKey(primaryKey);
					if(1 != numDeleted) {
						return(HttpUtils.notFoundResponse(APPLICATION_JSON, "{\"error\":\"primary key of '" +  primaryKeyString + "' not found.\"}"));
					}
					return(HttpUtils.okResponse());
				} catch (NumberFormatException | SQLException ex) {
					return(HttpUtils.internalServerErrorResponse(ex.getMessage()));
				}
			}
		}
		return(HttpUtils.forbiddenResponse());
	}

}
